<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>preview</LangVersion>
        <Description>Town Of Us Mira</Description>
        <RootNamespace>TownOfUs</RootNamespace>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
        <Configurations>Debug;Release;Publish</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
        <None Include="../LICENSE.txt" Pack="true" PackagePath="\"/>
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <Import Project="../AmongUs.props" Condition="'$(Configuration)' != 'Publish'"/>
    <Import Project="../AmongUsPublish.props" Condition="'$(Configuration)' == 'Publish'"/>
    
    <Target Name="CopyToPlugins" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)TownOfUsMira.dll" DestinationFolder="/Users/neiljain/Library/Application Support/CrossOver/Bottles/Mainly/drive_c/Program Files (x86)/Steam/steamapps/common/Among Us copy/BepInEx/plugins" />
    <Message Text="Copied $(AssemblyName).dll to BepInEx plugins folder!" Importance="High" />
  </Target>

</Project>